---
title: "biomass.Rmd"
author: "HM Putnam"
edited by: "Danielle Becker"
date: "20201024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("plotrix")) install.packages("plotrix")

# load packages
library(tidyverse)
library(plotrix)

```

```{r }
#Read in biomass data
Data <- read.csv("data/4_biomass/4_biomass_data.csv")
Data <- na.omit(Data)
  
# calculated mass per ml
#different volumes for sym (4ml) and host (5ml)
sym <- 5
host <- 4
Data <- Data %>%
  mutate(dry.pan.mass.g.ml = case_when(partner=="Host" ~ dry.pan.mass.g/sym, partner=="Sym" ~dry.pan.mass.g/host),
         burnt.pan.mass.g.ml = case_when(partner=="Host" ~ burnt.pan.mass.g/sym, partner=="Sym" ~burnt.pan.mass.g/host))

#Load tissue homogenate volume
homog_vol <- read.csv("data/4_homogenate_vols/4_homogenate_vols.csv", header=TRUE)

# Load Surface area data
sa <- read.csv("output/4_surface_area.csv")

# Coral sample metadata
metadata <- read_csv("../metadata/coral_metadata.csv") %>% select(1:3)

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vol) %>%
  full_join(sa)

# Join AFDW data with metadata
afdw <- left_join(Data, metadata) %>%
  mutate(dry.bioimass.g.ml = (dry.pan.mass.g.ml - burnt.pan.mass.g.ml),
         dry.bioimass.g = dry.pan.mass.g.ml * homog_vol_ml,
         burnt.bioimass.g = burnt.pan.mass.g.ml * homog_vol_ml,
         AFDW.mg.cm2 = ((dry.bioimass.g-burnt.bioimass.g)*1000) / surface.area.cm2)

# Calculate Dry Biomass
dw <- left_join(Data, metadata) %>% 
  mutate(dry.bioimass.g.ml = (dry.pan.mass.g.ml - burnt.pan.mass.g.ml),
         dry.bioimass.g = dry.pan.mass.g.ml * homog_vol_ml,
         DW.mg.cm2 = ((dry.bioimass.g)*1000) / surface.area.cm2)

```

Output biomass data to .csv.  

```{r}
afdw<-afdw %>%
  group_by(colony_id, partner)%>%
  summarise(AFDW.mg.cm2=mean(AFDW.mg.cm2))%>%
  left_join(.,metadata)%>% #add metadata back into file
  select(colony_id, partner, site, species, AFDW.mg.cm2) %>%
  mutate(timepoint="timepoint4")

dw<-dw %>% 
  group_by(colony_id, partner)%>%
  summarise(DW.mg.cm2=mean(DW.mg.cm2))%>%
  left_join(.,metadata)%>% #add metadata back into file
  select(colony_id, partner, site, species, DW.mg.cm2) %>%
  mutate(timepoint="timepoint4")
  
output<-left_join(afdw,dw)%>%
  write_csv(path = "output/4_biomass.csv")
```

```{r}
#summarize Dry Biomass mean and sem by site, species, and partner and plot
dw<-dw[!is.na(dw$species),]#remove rows that are not identified for species and site
dw<-dw[!is.na(dw$DW.mg.cm2),]#remove rows that do not have dw data

dw %>% #na.omit(dw) %>%
  group_by(species, site, partner)%>%
  summarise(mean.value = mean(DW.mg.cm2), se = std.error(DW.mg.cm2)) %>%
  ggplot(aes(x = site, y = mean.value, group = species, color = partner))+
  ylab("DW mg cm-2")+
  #ylim(0,700)+
  geom_point(size = 3)+
  geom_errorbar(aes(x = site, ymin = mean.value-se, ymax = mean.value+se), width = 0.5)+
  facet_grid(~species, scales = "free_y")


```

```{r}
#summarize AFDW mean and sem by site, species, and partner and plot
afdw<-afdw[!is.na(afdw$species),]#remove rows that are not identified for species and site
afdw<-afdw[!is.na(afdw$AFDW.mg.cm2),]#remove rows that do not have dw data

#remove outliers that are below zero for AFDW
afdw<-afdw%>%
  filter(AFDW.mg.cm2>0)

afdw %>% #na.omit(afdw) %>%
  group_by(species, site, partner)%>%
  summarise(mean.value = mean(AFDW.mg.cm2), se = std.error(AFDW.mg.cm2)) %>%
  ggplot(aes(x = site, y = mean.value, group = species, color = partner))+
  ylab("AFDW mg cm-2")+
  geom_point(size = 3)+
  geom_errorbar(aes(x = site, ymin = mean.value-se, ymax = mean.value+se), width = 0.5)+
  facet_grid(~species, scales = "free_y")


```

