---
title: "pH.Rmd"
author: "HM Putnam"
date: "1/17/2020"
output: html_document
---

#Title: pH by Site
#Project: E5
#Author: HM Putnam 
#Edited by: HM Putnam
#Date Last Modified: 20200117
#See Readme file for details

```{r setup, include = FALSE}
## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("dplyr")) install.packages("dplyr")
if (!require("plotrix")) install.packages("plotrix")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("lubridate")) install.packages("lubridate")

# load packages
library(tidyverse)
library(dplyr)
library(plotrix)
library(ggplot2)
library(lubridate)
```


```{r}
pH <- read.csv("data/1_environmental/1_20200102_SN20697597_Site1_pH.csv", header=F, sep=",", na.strings="NA", skip=700) #load  data
pH <- pH[,1:4]
colnames(pH) <- c("Date.Time", "Temp", "mV", "pH")
pH$Date.Time <- parse_date_time(pH$Date.Time, "Y!-m!*-d! H!:M!:S!") 

pdf("output/1_pH_Temp.pdf")
par(mfrow=c(3,1))
par(mar = c(5,5,2,5))
with(pH, plot(Date.Time, pH, type="l", col="blue", 
             ylim=c(7.9,8.5), ylab =NA, main="Site 1"))
axis(2, col="blue",col.axis="blue")
mtext("pH",side=2,col="blue",line=4) 
par(new = T)
with(pH, plot(Date.Time, Temp,type="l", axes=F,col="black", xlab=NA, ylab=NA, ylim=c(27,32)))
axis(side = 4)
mtext(side = 4, line = 3, 'Temperature°C')
#dev.off()

pH <- read.csv("data/1_environmental/1_20200103_SN20697596_Site2_pH.csv", header=F, sep=",", na.strings="NA", skip=700) #load  data
pH <- pH[,1:4]
colnames(pH) <- c("Date.Time", "Temp", "mV", "pH")
pH$Date.Time <- parse_date_time(pH$Date.Time, "Y!-m!*-d! H!:M!:S!") 

#pdf("output/20200103_Site2_pH_Temp.pdf")
par(mar = c(5,5,2,5))
with(pH, plot(Date.Time, pH, type="l", col="blue", 
              ylim=c(7.9,8.5), ylab =NA, main="Site 2"))
axis(2, col="blue",col.axis="blue")
mtext("pH",side=2,col="blue",line=4) 
par(new = T)
with(pH, plot(Date.Time, Temp,type="l", axes=F,col="black", xlab=NA, ylab=NA, ylim=c(27,32)))
axis(side = 4)
mtext(side = 4, line = 3, 'Temperature°C')
#dev.off()

pH <- read.csv("data/1_environmental/1_20200106_SN20697595_Site3_pH.csv", header=F, sep=",", na.strings="NA", skip=700) #load  data
pH <- pH[,1:4]
colnames(pH) <- c("Date.Time", "Temp", "mV", "pH")
pH$Date.Time <- parse_date_time(pH$Date.Time, "Y!-m!*-d! H!:M!:S!") 

#pdf("output/20200103_Site3_pH_Temp.pdf")
par(mar = c(5,5,2,5))
with(pH, plot(Date.Time, pH, type="l", col="blue", 
              ylim=c(7.9,8.5), ylab =NA, main="Site 3"))
axis(2, col="blue",col.axis="blue")
mtext("pH",side=2,col="blue",line=4) 
par(new = T)
with(pH, plot(Date.Time, Temp,type="l", axes=F,col="black", xlab=NA, ylab=NA, ylim=c(27,32)))
axis(side = 4)
mtext(side = 4, line = 3, 'Temperature°C')
dev.off()
```
