---
title: "biomass.Rmd"
author: "HM Putnam"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("plotrix")) install.packages("plotrix")

# load packages
library(tidyverse)
library(plotrix)

```

```{r }
#Read in biomass data
Data <- read.csv("data/1_biomass/1_biomass_data.csv")
Data <- na.omit(Data)
# Change POC-42 pan 221 from Sym to Host -- was recorded twice as Sym, assuming pan with more mass is host
Data[Data$Pan.ID == 221, "partner"] <- "Host"
  
# set sample volumes to calculated mass per ml of sample added to pans
#different volumes for sym (4ml) and host (5ml)
sym.vol <- 5
host.vol <- 4

#Load tissue homogenate volume
homog_vol <- read.csv("data/1_homogenate_vols/1_homogenate_vols.csv", header=TRUE)

# Load Surface area data
sa <- read.csv("output/1_surface_area.csv")

# Coral sample metadata
metadata <- read_csv("../metadata/coral_metadata.csv") %>% select(1:3)

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vol) %>%
  full_join(sa)

# Join AFDW data with metadata
afdw <- left_join(Data, metadata) %>%
  mutate(dry.biomass.g = dry.pan.mass.g - initial.mass.g,
         burnt.biomass.g = dry.pan.mass.g - burnt.pan.mass.g,
         dry.biomass.g.ml = case_when(partner == "Host" ~ dry.biomass.g / host.vol, 
                                      partner == "Sym"  ~ dry.biomass.g / sym.vol),
         burnt.biomass.g.ml = case_when(partner == "Host" ~ dry.biomass.g / host.vol, 
                                        partner == "Sym"  ~ dry.biomass.g / sym.vol),
         dry.biomass.g.coral = dry.biomass.g.ml * homog_vol_ml,
         burnt.biomass.g.coral = burnt.biomass.g.ml * homog_vol_ml,
         DW.mg.cm2 = ((dry.biomass.g.coral)*1000) / surface.area.cm2,
         AFDW.mg.cm2 = ((burnt.biomass.g.coral)*1000) / surface.area.cm2)

# Filter out samples that are duplicated in the dataset (one of them might have been different sample with a data entry error, but no way to know for sure)
afdw <- afdw %>%
  group_by(colony_id) %>%
  summarise(n = n()) %>%
  filter(n == 2) %>%
  left_join(afdw) %>%
  ungroup()


```


```{r}
#summarize Dry Biomass mean and sem by site, species, and partner and plot
afdw %>% 
  drop_na() %>%
  group_by(species, site, partner)%>%
  summarise(mean.value = mean(DW.mg.cm2), se = std.error(DW.mg.cm2)) %>%
  ggplot(aes(x = site, y = mean.value, group = species, color = partner))+
  ylab("DW mg cm-2")+
  geom_point(size = 3)+
  geom_errorbar(aes(x = site, ymin = mean.value-se, ymax = mean.value+se), width = 0.5)+
  facet_grid(~species, scales = "free_y")


```

```{r}
#summarize AFDW mean and sem by site, species, and partner and plot
afdw %>%
  drop_na() %>%
  ggplot(aes(x = site, y = AFDW.mg.cm2, color = partner, group = partner)) +
  facet_wrap(~species, scales = "free") +
  labs(x = "", y = "AFDW (mg/cm2)") +
  geom_point(position = position_jitterdodge(dodge.width = 0.75, jitter.width = 0.1), alpha = 0.6) +            # Plot all points
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", width = 0.5, position = position_dodge(width = 0.75)) +
  stat_summary(fun.y = mean, geom = "point", size = 3, pch = 1, position = position_dodge(width = 0.75))           # Plot mean

```

```{r}
# Symbiont to host biomass ratio for each sample
sh <- tibble(afdw) %>%
  drop_na() %>%
  select(colony_id, site, species, partner, AFDW.mg.cm2) %>%
  pivot_wider(names_from = partner, values_from = AFDW.mg.cm2) %>%
  mutate(SH = Sym / Host)

sh %>%
  ggplot(aes(x = site, y = SH, color = species)) +
  facet_wrap(~species) +
  labs(x = "", y = "S/H biomass ratio") +
  geom_point(position = position_jitter(width = 0.1), alpha = 0.6) +            # Plot all points
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", width = 0.25) +
  stat_summary(fun.y = mean, geom = "point", size = 3, pch = 1)           # Plot mean

```

