---
title: "Chlorophyll analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("plotrix")) install.packages("plotrix")

# load packages
library(tidyverse)
library(plotrix)
```

# Import data
```{r}
# Define function to read in chl data
read_chl <- function(file) {
  chl_data <- read_csv(file, skip = 24, n_max = 24) %>%
    select(-1) %>%
    magrittr::set_colnames(c("row", 1:12, "wavelength")) %>%
    fill(row) %>%
    gather("col", "absorbance", -wavelength, -row) %>%
    unite("well", c(row, col), sep = "")
}

# List chlorophyll data files
chl_path = "data/1_Chl/"                                                 # Path to chl data directory
all_chl_files <- list.files(path = chl_path, pattern = "*.csv")          # List all files in directory
chl_platemaps <- list.files(path = chl_path, pattern = "platemap")       # List platemap files
chl_data_files <- setdiff(all_chl_files, chl_platemaps)                  # List absorbance data files

# Read in all files into tibble
df <- tibble(file = chl_data_files) %>%
  mutate(platemap = map(file, ~ read_csv(paste0(chl_path, tools::file_path_sans_ext(.), "_platemap.csv"))),
         chl_data = map(file, ~ read_chl(paste0(chl_path, .))))

# Merge platemap and data for each plate
df <- df %>%
  mutate(merged = map2(platemap, chl_data, ~ right_join(.x, .y)))
```

# Calculate chlorophyll concentrations
```{r}
# average all technical replicates for each plate/sample/wavelength, including all acetone blanks together (per plate)
df <- df %>%
  unnest(merged) %>%
  filter(!is.na(colony_id)) %>%                         # remove empty wells (colony_id is NA)
  group_by(file, colony_id, wavelength) %>%
  summarise(n = n(), mean_abs = mean(absorbance)) %>%
  spread(wavelength, mean_abs)

# get the acetone blank 750 absorbace for each file (i.e., plate), and subtract from 630 and 663 values for each sample
df <- df %>%
  group_by(file) %>%
  mutate(blank750 = `750`[colony_id == "BK"]) %>%
  ungroup() %>%
  mutate(adj630 = `630` - blank750,
         adj663 = `663` - blank750)

# calculate chla and chlc2 values based on equations from Jeffrey and Humphrey 1975
#units µg/ml
df <- df %>%
  mutate(chla = 11.43 * adj663 - 0.64 * adj630,
        chlc2 = 27.09 * adj630 - 3.63 * adj663)
```

# Normalize to surface area
```{r}
#Load homogenate volume
homog.vol <- read_csv("data/1_homogenate_vols.csv") %>%
  select(colony_id, homog_vol_ml)

Data <- full_join(df, homog.vol)
# Load surface area
sa <- read_csv("output/coral_surface_area.csv")
Data <- full_join(Data, sa)

#Multiply by the homogenate volume and divide by surface area
Data$chla.cm2 <-  (Data$chla * Data$homog_vol_ml)/Data$surface.area.cm2
Data$chlc2.cm2 <-  (Data$chlc2 * Data$homog_vol_ml)/Data$surface.area.cm2

# remove blanks and NAs
Data <- filter(Data, !colony_id %in% c("NA", "BK"))

# write chlorophyll data to file
Data %>%
  select(colony_id, chla.cm2, chlc2.cm2) %>%
  write_csv(path = "output/1_chl.csv")
```

# Plot
```{r, eval = TRUE}
# Join with sample metadata
Meta <- read_csv("../metadata/coral_metadata.csv")
Data <- full_join(Data, Meta, by = "colony_id")

Data%>%
  group_by(species, site) %>%
  summarise(mean.value = mean(chla.cm2, na.rm = TRUE), se = std.error(chla.cm2, na.rm = TRUE)) %>%
  ggplot(aes(x = site, y = mean.value, group = species, color = species))+
  ylab("CHL-a µg cm-2")+
  geom_point(size = 3)+
  geom_errorbar(aes(x = site, ymin = mean.value-se, ymax = mean.value+se), width = 0.5)+
  facet_grid(~species, scales = "free_y")

Data%>%
  group_by(species, site) %>%
  summarise(mean.value = mean(chlc2.cm2, na.rm = TRUE ), se = std.error(chlc2.cm2, na.rm = TRUE )) %>%
  ggplot(aes(x = site, y = mean.value, group = species, color = species))+
  ylab("CHL-c2 µg cm-2")+
  geom_point(size = 3)+
  geom_errorbar(aes(x = site, ymin = mean.value-se, ymax = mean.value+se), width = 0.5)+
  facet_grid(~species, scales = "free_y")
```


