---
title: "Photosynthesis parameters summary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plotrix)
library(Hmisc)
```

# Import PI curve fitted parameters for each individual
```{r}
pars <- read_csv("output/1_pi_curve_pars.csv")
```

# Import sample metadata
```{r}
md <- read_csv("../metadata/coral_metadata.csv")

df <- left_join(pars, md)
```

# Plot data with mean ± SE for each species/site
```{r, fig.height = 10}
# Facet grid with common y-scale for each variable
df %>%
  filter(!.variable %in% c("sigma", "b_theta_Intercept", NA)) %>%
  ggplot(aes(x = site, y = .value, color = species)) +
  facet_grid(.variable~species, scales = "free_y") +
  geom_jitter(width = 0.1) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.5) +
  stat_summary(fun.y = mean, geom = "point", color = "black")   

# Facet wrap for free y-scale on each facet
df %>%
  filter(!.variable %in% c("sigma", "b_theta_Intercept", NA)) %>%
  ggplot(aes(x = site, y = .value, color = species)) +
  facet_wrap(~.variable+species, scales = "free_y", ncol = 3) +
  geom_jitter(width = 0.1) +
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.5) +
  stat_summary(fun.y = mean, geom = "point", color = "black")    
```
