---
title: "pi_curves_nls"
author: "Ariana S Huffmyer"
date: "3/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
```

```{r load_packages}
## install packages if you dont already have them in your library
if ("devtools" %in% rownames(installed.packages()) == 'FALSE') install.packages('devtools') 
if ("segmented" %in% rownames(installed.packages()) == 'FALSE') install.packages('segmented') 
if ("plotrix" %in% rownames(installed.packages()) == 'FALSE') install.packages('plotrix') 
if ("gridExtra" %in% rownames(installed.packages()) == 'FALSE') install.packages('gridExtra') 
if ("LoLinR" %in% rownames(installed.packages()) == 'FALSE') install_github('colin-olito/LoLinR') 
if ("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if ("chron" %in% rownames(installed.packages()) == 'FALSE') install.packages('chron') 
if ("plyr" %in% rownames(installed.packages()) == 'FALSE') install.packages('plyr') 
if ("dplyr" %in% rownames(installed.packages()) == 'FALSE') install.packages('dplyr') 
if ("phytotools" %in% rownames(installed.packages()) == 'FALSE') install.packages('phytotools') 

#Read in required libraries

library("devtools")
library("ggplot2")
library("segmented")
library("plotrix")
library("gridExtra")
library("LoLinR")
library("lubridate")
library("chron")
library('plyr')
library('dplyr')
library('phytotools')
```

# Import data
```{r import_data}
Data <- read.csv(file = 'output/1_pi_curve_rates.csv')
#Data <- Data[1:40,]
```


# Define data  

```{r}
PAR <- as.numeric(Data$Light_Value)
Pc <- as.numeric(Data$micromol.cm2.h)
plot(PAR,Pc,xlab="", ylab="", xlim=c(0,max(PAR)), ylim=c(-2, 2), cex.lab=0.8,cex.axis=0.8,cex=1, main="", adj = 0.05) #set plot info
mtext(expression("Irradiance ("*mu*"mol photons "*m^-2*s^-1*")"),side=1,line=3.3,cex=1) #add labels
mtext(expression(Rate*" ("*mu*"mol "*O[2]*" "*cm^-2*h^-1*")"),side=2,line=2,cex=1) #add labels
```

# Define PI curve function as a nonlinear Least Squares regression of a quadratic fit

```{r}
#Aquatic Photosynthesis, Falkowski 
#Pmax = max photosynthesis (AKA Am from Bayesian script)
#alpha = quantum yeild (AKA AQY from Bayesian script)
#I/E = irradiance (AKA PAR from Bayesian script)
#Rd = dark respiration 


#Currently running into an error on this line: 
curve.nlsrc = nls(Pc ~ (Am*((AQY*PAR)/(sqrt(Am^2+(AQY*PAR^2))))-Rd), start=list(Am=(max(Pc)-min(Pc)), AQY=0.05, Rd=abs(min(Pc))))
my.fit <- summary(curve.nlslrc) #summary of model fit
```






```{r}
#draw the curve using the model fit
Ber.curve.fitting <- curve((1/(2*summary(curve.nlslrc)$coef[4,1]))*(summary(curve.nlslrc)$coef[2,1]*x+summary(curve.nlslrc)$coef[1,1]-sqrt((summary(curve.nlslrc)$coef[2,1]*x+summary(curve.nlslrc)$coef[1,1])^2-4*summary(curve.nlslrc)$coef[2,1]*summary(curve.nlslrc)$coef[4,1]*summary(curve.nlslrc)$coef[1,1]*x))-summary(curve.nlslrc)$coef[3,1],lwd=2,col="blue",add=T)
dev.off()


#need to run for each colony:
Data <- Data %>%
  nest(-colony_id) %>%
  mutate(fit = furrr::future_map(data, ~ fit_pi_curve_noerror(.)))
```

# Extract parameters values and 95% confidence intervals
```{r extract_pars}
# Define function to extract parameter values and CI's from fitted model object
getpars <- function(x) {
  x %>% 
    gather_draws(b_AQY_Intercept, b_Am_Intercept, b_theta_Intercept, b_Rd_Intercept, sigma, Ic) %>%
    median_qi()
}
# Function to get parameters, but return NULL in case of error (where model fitting failed)
getpars_noerror <- possibly(getpars, otherwise = NULL)

# Get parameter values for all individuals
Data <- Data %>%
  mutate(pars = map(fit, getpars_noerror))
```

# Write PI curve parameters to file
```{r save_pars}
# Unnest parameter values
pars.out <- Data %>%
  select(colony_id, pars) %>%
  unnest(cols = pars)

# Join with colony_id to create rows of NA for individuals that failed Bayesian fitting
pars.out2 <- Data %>% 
  select(colony_id) %>%
  left_join(pars.out) %>%
  mutate(timepoint="timepoint1")

write_csv(pars.out2, "output/1_pi_curve_pars.csv")
```

# Create plots for all individuals
```{r create_plots}
# Create plots for all individuals
Data <- Data %>%
  drop_na() %>%      # Drops individuals that didn't fit
  mutate(
    plot = pmap(list(colony_id = colony_id, data = data, fit = fit, pars = pars),
                     function(colony_id, data, fit, pars) {
      pt <- marginal_effects(fit)
      ggplot(as.data.frame(pt$Light_Value)) +      # pull the fitted data
        geom_line(aes(Light_Value, estimate__)) +  #
        geom_ribbon(aes(Light_Value, ymin = lower__, ymax = upper__), alpha = 0.3) +
        geom_point(data = data, aes(x = Light_Value, y = micromol.cm2.h)) +    # add the raw data
        geom_hline(yintercept = pars %>% filter(.variable == "b_Am_Intercept") %>% pull(.value), lty = 2) +
        geom_hline(yintercept = pars %>% filter(.variable == "b_Rd_Intercept") %>% pull(.value) * -1, lty = 2) +
        geom_abline(intercept = pars %>% filter(.variable == "b_Rd_Intercept") %>% pull(.value) * -1,
                    slope = pars %>% filter(.variable == "b_AQY_Intercept") %>% pull(.value), lty = 2) +
        theme_bw() +
        theme(text = element_text(size=18), title = element_text(face="italic")) +
        labs(x = expression(paste('PAR (', mu, "mol photons m"^-2, 's'^-1,")")),
             y = expression(paste('Photosynthetic rate (', mu, "mol cm"^-2, 'h'^-1,")")),
             title = paste0("1_", colony_id))
      }))
```

# Save PI curve plots to files
```{r save_plots}
Data %>%
  mutate(filename = paste0("output/1_pi_curve_plots/1_", colony_id, ".pdf")) %>%
  select(filename, plot) %>%
  pwalk(ggsave)
```

