---
title: "TAC analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")

# load packages
library(tidyverse)
```


```{r}
# Function to read in TAC data
read_tac <- function(file) {
  tac_data <- read_csv(file, skip = 23, n_max = 24) %>%
    select(-1) %>%
    magrittr::set_colnames(c("row", 1:12, "wavelength")) %>%
    gather("col", "absorbance", -wavelength, -row) %>%
    unite("well", c(row, col), sep = "")
}

# List chlorophyll data files
tac_path = "data/1_TAC/"                                                 # Path to TAC data directory
all_tac_files <- list.files(path = tac_path, pattern = "*.csv")          # List all files in directory
tac_platemaps <- list.files(path = tac_path, pattern = "platemap")       # List platemap files
tac_data_files <- setdiff(all_tac_files, tac_platemaps)                  # List data files

# Read in all files into tibble
df <- tibble(file = tac_data_files) %>%
  separate(file, into = c("trip", "date", "plate", "readtime"), remove = FALSE) %>%
  unite(plate, trip, date, plate) %>%
  mutate(platemap = map(plate, ~read_csv(paste0(tac_path, ., "_TAC_platemap.csv"))),
         tac_data = map( file, ~read_tac(paste0(tac_path, .))))

# Merge platemap and data for each plate
df <- df %>%
  mutate(merged = map2(platemap, tac_data, ~ right_join(.x, .y)))
```

```{r}
standards <- tribble(
  ~std, ~conc_mM,
  1,           1,
  2,         0.5,
  3,        0.25,
  4,       0.125,
  5,      0.0625,
  6,     0.03125,
  7,     0.01560,
  8,     0.00780,
  9,     0.00390,
 10,           0
)

std_curve <- df %>%
  unnest(merged) %>%
  filter(grepl("Standard", colony_id)) %>%
  select(plate, well, colony_id, wavelength, absorbance, readtime) %>%
  rename(std = colony_id) %>%
  mutate(std = as.numeric(str_sub(std, 9, 10))) %>%
  spread(readtime, absorbance) %>%
  mutate(net = final - initial) %>%
  group_by(std) %>%
  summarise(net = mean(net)) %>%
  mutate(net.adj = net - net[std == 10]) %>%
  left_join(standards)

mod <- nls(formula = conc_mM ~ z + a * exp(b * net.adj), start = list(z = 0, a = 1, b = 1), data = std_curve)
fitted <- mod %>% broom::augment()

std_curve_plot <- std_curve %>%
  ggplot(aes(x = net.adj, y = conc_mM)) +
  geom_point(color = "red")

std_curve_plot + geom_line(data = fitted, aes(x = net.adj, y = .fitted))
```


```{r}
tac <- df %>%
  unnest(merged) %>%
  filter(!grepl("Standard", colony_id)) %>%
  select(plate, well, colony_id, wavelength, absorbance, readtime) %>%
  spread(readtime, absorbance) %>%
  mutate(net = final - initial,
         net.adj = net - std_curve$net[std_curve$std == 10],
         uae.mmol.L = map_dbl(net.adj, ~ predict(mod, newdata = data.frame(net.adj = .))))

std_curve_plot +
  geom_point(data = tac, aes(x = net.adj, y = uae.mmol.L), pch = "X", cex = 3, alpha = 0.3) 
  #geom_segment(data = tac, aes(x = 0, xend = net.adj, y = uae.mmol.L, yend = uae.mmol.L), lwd = 0.1) +
  #geom_segment(data = tac, aes(x = net.adj, xend = net.adj, y = 0, yend = uae.mmol.L), lwd = 0.1)
```

```{r}
# Surface area data
sa <- read.csv("output/coral_surface_area.csv") %>%
  group_by(colony_id) %>%                                  # Average surface area measurements if multiple per coral 
  summarise(surface.area.cm2 = mean(surface.area.cm2))

# Tissue homogenate volume data
homog_vols <- read_csv("data/1_homogenate_vols.csv") %>% select(1:2)

# Coral sample metadata
metadata <- read_csv("../metadata/coral_metadata.csv") %>% select(1:3)

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vols) %>%
  full_join(sa)

# Join TAC data with metadata
tac <- left_join(tac, metadata) %>%
  mutate(uae.mmol = uae.mmol.L * (homog_vol_ml / 1000),
         uae.mmol.cm2 = uae.mmol / surface.area.cm2)
```

```{r}
tac %>%
  filter(!is.na(species)) %>%
  ggplot(aes(x = site, y = uae.mmol.cm2, color = species)) +
  geom_hline(yintercept = 0) +
  facet_wrap(~species) +
  geom_boxplot() +
  geom_point()

tac %>%
  group_by(species, site) %>%
  summarise(mean_tac = mean(uae.mmol.cm2, na.rm = T))
```

```{r}
# Normalize TAC to protein

prot <- read_csv("output/1_Protein.csv")

tac <- tac %>%
  select(colony_id, uae.mmol, uae.mmol.cm2) %>%
  left_join(prot) %>%
  mutate(uae_mmol.ugprot = uae.mmol / prot_ug)


tac %>%
  drop_na() %>%
  left_join(metadata) %>%
  ggplot(aes(x = site, y = log10(uae_mmol.ugprot), color = species)) +
  facet_wrap(~species) +
  geom_boxplot() +
  geom_point()
```

