---
title: "Total Antioxidant Capacity (TAC) analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("broom")) install.packages("broom")

# load packages
library(tidyverse)
library(broom)
```

# Import data
```{r}
# Function to read in TAC data
read_tac <- function(file) {
  tac_data <- read_csv(file, skip = 23, n_max = 24) %>%
    select(-1) %>%
    magrittr::set_colnames(c("row", 1:12, "wavelength")) %>%
    gather("col", "absorbance", -wavelength, -row) %>%
    unite("well", c(row, col), sep = "")
}

# List TAC data files
tac_path = "data/2_antioxidant_capacity/"                                                 # Path to TAC data directory
all_tac_files <- list.files(path = tac_path, pattern = "*.csv")          # List all files in directory
tac_platemaps <- list.files(path = tac_path, pattern = "platemap")       # List platemap files
tac_data_files <- setdiff(all_tac_files, tac_platemaps)                  # List data files

# Read in all files into tibble
df <- tibble(file = tac_data_files) %>%
  separate(file, into = c("trip", "date", "plate", "readtime"), remove = FALSE) %>%
  unite(plate, trip, date, plate) %>%
  mutate(platemap = map(plate, ~read_csv(paste0(tac_path, ., "_TAC_platemap.csv"))),
         tac_data = map( file, ~read_tac(paste0(tac_path, .))))

# Merge platemap and data for each plate
df <- df %>%
  mutate(merged = map2(platemap, tac_data, ~ right_join(.x, .y)))
```

# Plot standard curve
```{r}
# Create standards following kit instructions
standards <- tribble(
  ~std, ~conc_mM,
  1,           1,
  2,         0.5,
  3,        0.25,
  4,       0.125,
  5,      0.0625,
  6,     0.03125,
  7,     0.01560,
  8,     0.00780,
  9,     0.00390,
 10,           0
)

std_curve <- df %>%
  unnest(merged) %>%
  filter(grepl("Standard", colony_id)) %>%
  select(plate, well, colony_id, wavelength, absorbance, readtime) %>%
  rename(std = colony_id) %>%
  mutate(std = as.numeric(str_sub(std, 9, 10))) %>%
  spread(readtime, absorbance) %>%
  mutate(net_abs = final - initial) %>%
  left_join(standards)

# Fit nonlinear model
nlmod <- nls(formula = conc_mM ~ z + a * exp(b * net_abs), start = list(z = 0, a = 1, b = 1), data = std_curve)
# Fit linear model
lmod <- lm(conc_mM ~ net_abs, data = std_curve)

# Get fitted values
fitted <- nlmod %>% 
  broom::augment(newdata = tibble(net_abs = seq(0, max(std_curve$net_abs), 0.005)))

std_curve_plot <- std_curve %>%
  ggplot(aes(x = net_abs, y = conc_mM)) +
  geom_point(color = "red", size = 3)

std_curve_plot + geom_line(data = fitted, aes(x = net_abs, y = .fitted)) +
  labs(title = "Standard curve")
```

# Calculate total antioxidant capacity for all samples based on standard curve
```{r}
tac <- df %>%
  unnest(merged) %>%
  filter(!grepl("Standard", colony_id)) %>%
  select(plate, well, colony_id, wavelength, absorbance, readtime) %>%
  spread(readtime, absorbance) %>%
  # Use standard curve to predict concentrations based on sample absorbance values
  mutate(net_abs = final - initial,
         uae.mmol.L = map_dbl(net_abs, ~ predict(nlmod, newdata = data.frame(net_abs = .))))

std_curve_plot +
  geom_point(data = tac, aes(x = net_abs, y = uae.mmol.L), pch = "X", cex = 3, alpha = 0.3) +
    labs(title = "All samples projected on standard curve")
```

# Normalize to surface area and protein
```{r}
# Tissue homogenate volume data
homog_vols <- read_csv("data/2_homogenate_vols/2_homogenate_vols.csv") %>% select(1:2)

# Protein data
prot <- read_csv("output/2_protein.csv")

# Coral sample metadata
metadata <- read_csv("../metadata/coral_metadata.csv") %>% select(1:3)

# Join homogenate volumes with sample metadata
metadata <- full_join(metadata, homog_vols) %>%
  full_join(prot)

# Join TAC data with metadata
tac <- left_join(tac, metadata) %>%
  mutate(cre.umol.L = uae.mmol.L * 2189) %>%   # Convert to CRE (see product manual) per unit sample volume
  mutate(cre.umol = cre.umol.L * (homog_vol_ml / 1000),  # Convert to CRE per coral by multiplying by homog. vol.
         cre.umol.mgprot = cre.umol / (prot_ug / 1000))  # Convert to CRE per mg protein by dividing by total protein
```

# Plot results by species and site
```{r}
# Plot all data points with mean ± se
tacplot <- tac %>%
  filter(!is.na(species)) %>%
  ggplot(aes(x = site, y = cre.umol.mgprot, color = species)) +
  facet_wrap(~species)  +
  coord_cartesian(ylim = c(0, 2))+
  labs(x = "", y = "Copper Reducing Equivalents (µmol/mg protein)",
       title = "Total antixodidant capacity") +
  geom_jitter(width = 0.1) +                                            # Plot all points
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.5) +
  stat_summary(fun.y = mean, geom = "point", color = "black")           # Plot mean

tacplot
```

### Summarize results
```{r}
tac %>% 
  drop_na(species) %>%
  group_by(species) %>%
  summarise(across(cre.umol.mgprot, list(mean = mean, min = min, max = max), na.rm = TRUE))
```

# Write data to output file
```{r}
tac %>%
  filter(!is.na(species)) %>%
  select(colony_id, cre.umol.L, cre.umol.mgprot) %>%
  write_csv(., path = "output/2_antioxidant_capacity.csv")
```


