---
title: "Calcification Total Alkalinity"
author: "Nyssa Silbiger, Danielle Becker, edited by Ariana S Huffmyer"
date: "5/6/2021"
output:
  html_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
```

```{r load_packages}
## install packages if you dont already have them in your library
if ("tidyverse" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse') 
if ("broom" %in% rownames(installed.packages()) == 'FALSE') install.packages('broom') 
if ("purrr" %in% rownames(installed.packages()) == 'FALSE') install.packages('purrr') 
if ("lubridate" %in% rownames(installed.packages()) == 'FALSE') install.packages('lubridate') 
if ("nlstools" %in% rownames(installed.packages()) == 'FALSE') install.packages('nlstools')
if ("stringr" %in% rownames(installed.packages()) == 'FALSE') install.packages('stringr') 

#Read in required libraries

library(broom)
library(purrr)
library(lubridate)
library(tidyverse)
library(nlstools)
library(stringr)
```

# Import data and format
```{r import_data}
#bring in calcification data file with TA and chamber pH, temp, salinity measurements
calc.data <- read.csv("data/2_calcification/2_TA_data.csv")

#create new data frame of just the initial data (initial bottles taken before each run for initial TA measurements), pull out initial data from sample.type
```

Normalize TA values to salinity and separate blanks from samples.  
```{r}
#add salinity normalization for TA values for blanks
#add new column for TA initial normalized and TA normalized, then include TA.norm values below 
calc.data$Ta.norm<-calc.data$TA*calc.data$salinity.lab/36

rows.initial <- which(calc.data$sample.type == "Initial") #tells you all the rows that you have with initial sample type

initial <- calc.data[rows.initial,] #shows you the rows with the initial sample type

calc.data <- calc.data[-rows.initial,] #to remove the rows with initial data

#remove and create new data frame with just blanks

rows.blanks <- which(calc.data$sample.type == "Blank") #tells you all the rows that you have wwith blanks

blanks <-calc.data[rows.blanks,] #shows you the rows with the blank sample type

calc.data <- calc.data[-rows.blanks,] #to remove the rows with blank data

#need to join sample data frame, join initial with your calc.data, only by run number, pull out the columns we need

initial <- initial[, c("date","run.number", "salinity.chamber", "salinity.lab", "TA", "mV.chamber", "Ta.norm")]
names(initial)[3:7] <- paste0(names(initial)[3:7], "_initial") #use this to rename all of our columns

#join blanks and carb chem data frame

calc.data <- left_join(calc.data, initial) #joining the initials to the data frame for carb chem
blanks <- left_join(blanks,initial)
```

Calculate delta TA and mean blank values.  
```{r}
#figure out delta TA, initial-final

blanks$delta.TA.blank <- blanks$Ta.norm_initial - blanks$Ta.norm

#getting the averages of blanks for each temperature and each date
mean.blanks <- blanks %>% 
  group_by(date) %>%
  summarise(mean.blanks=mean(delta.TA.blank))

calc.data <- left_join(calc.data, mean.blanks) #bring in mean blanks to calc.data

#need to join in SA, time data by colony ID, before calculating NEC
```

Read in metadata and surface area data.  
```{r}
sample.data <- read.csv("../timepoint_2/output/2_surface_area.csv") #bring in SA and volume data sheet

SA <- sample.data[, c("colony_id", "surface.area.cm2")] #pull out the necessary columns and treatment 

calc.data2 <- left_join(calc.data, SA) # join carb chem and SA data

#bring in the time data from resp.data sheet
resp.data <- read.csv("data/2_calcification/2_DeltaTA_metadata.csv")

#pull out columns that we want to use for our bind to the calc.data2 sheet

time.data <- resp.data[, c("colony_id","TA.Start.Time", "TA.Stop.Time")] 

full.calc.data <- left_join(calc.data2, time.data)
```

Adjust time information.  
```{r}
#adjust the time information and format

#convert time from character to time
full.calc.data$start.time <- strptime(as.character(full.calc.data$TA.Start.Time), "%I:%M:%S %p")

#convert time from character to time
full.calc.data$stop.time <- strptime(as.character(full.calc.data$TA.Stop.Time), "%I:%M:%S %p")
```

Calculate Net Ecosystem Calcification (NEC) from total alkalinity method.  
```{r}
#calculate the net ecosystem calcification rate

full.calc.data$deltaTA<- (full.calc.data$Ta.norm_initial - full.calc.data$Ta.norm) - full.calc.data$mean.blanks
full.calc.data$timediff <- as.numeric((full.calc.data$stop.time - full.calc.data$start.time)) 

#convert volume (L) to mL 
#equation to calculate NEC rates 

full.calc.data$umol.cm2.hr <- (full.calc.data$deltaTA/2)*(1.023)*((full.calc.data$vol.L*1000)/full.calc.data$surface.area.cm2)*(1/full.calc.data$timediff)*(1/1000)

#anything that it <0 make it zero
full.calc.data$umol.cm2.hr[full.calc.data$umol.cm2.hr<0]<-0

#log x+ 1 you will have to log x + whatever the difference is here, a line for dissolution and calcification
#full.calc.data$log.umol.cm2.hr <- log10(1+full.calc.data$umol.cm2.hr) 

full.calc.data%>%
  mutate(timepoint="timepoint2")%>%
  drop_na()%>%
  write.csv(., 'output/2_calcification_rates.csv') 
```


Plot data.  
```{r}
full.calc.data %>%
  filter(!run.number=="NA")%>%
  filter(!species=="NA")%>%
  filter(!site=="NA")%>%
  ggplot(aes(x = as.factor(site), y = umol.cm2.hr, color = species), position=position_dodge(0.5)) +
  geom_boxplot()+
  geom_point(size=3)+
  facet_wrap(~species) +
  labs(x = "Site", y = expression(paste(mu,"mol CaCO3 cm"^-2, "hr"^-1))) +                                       # Plot all points
  theme_classic() 
```