---
title: "Check completeness of datasets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")

# load packages
library(tidyverse)
```

### Import `colony_id` from each dataset
```{r}
coral_metadata <- read_csv("../metadata/coral_metadata.csv") %>% 
  pull(colony_id)

homog_vols <- read_csv("data/3_homogenate_vols/3_homogenate_vols.csv") %>% 
  pull(colony_id)

surface_area <- read_csv("data/3_surface_area/3_surface_area_data.csv") %>% 
  filter(!grepl("Standard", Sample)) %>%
  pull(colony_id)

chl <- list.files("data/3_chlorophyll/", "platemap", full.names = TRUE) %>%
  map_df(read_csv) %>%
  drop_na() %>%
  filter(!colony_id == "BK") %>%
  pull(colony_id)

afdw <- read_csv("data/3_biomass/3_biomass_data.csv") %>%
  drop_na() %>%
  pull(colony_id)

molec <- read_csv("data/3_molecular_backups/3_molecular_backups.csv") %>%
  distinct(colony_id) %>%
  pull()

picurve <- list.files("data/3_pi_curves/", "*.csv") %>%
  gsub("_.*.csv", "", .) %>%
  subset(!grepl("BK", .))

sym_counts <- read_csv("data/3_sym_counts/3_sym_counts_data.csv") %>%
  pull(colony_id)

#tac

tac <- list.files("data/3_antioxidant_capacity/", "platemap", full.names = TRUE) %>%
  map_df(read_csv) %>%
  drop_na() %>%
  filter(!colony_id == "BK") %>%
  pull(colony_id)

#protein

protein <- list.files("data/3_protein/", "platemap", full.names = TRUE) %>%
  map_df(read_csv) %>%
  drop_na() %>%
  filter(!colony_id == "BK") %>%
  pull(colony_id)

```

### Filter out `colony_id` of any corals we know were *not collected*
```{r}
coral_metadata <- coral_metadata %>%
  .[!. %in% c("ACR-165", "ACR-176", "ACR-180", "ACR-185", "ACR-187", "ACR-193", "ACR-228", "ACR-231", "ACR-234", "ACR-243", "ACR-246", "ACR-247", "ACR-256", "ACR-258", "ACR-267", "ACR-345", "ACR-347", "ACR-350", "ACR-351", "ACR-363", "ACR-368", "ACR-374", "ACR-379", "ACR-389", "ACR-390", "ACR-393", "ACR-396", "ACR-51", "POC-217", "POC-346", "POC-394", "POC-41", "POC-56", "POR-235", "POR-236", "POR-266", "POR-77", "POR-78", "ACR-370", "ACR-376", "ACR-360", "POC-215", "POC-232", "POR-206")]
```

## Are there mystery samples in any of the datasets that are not part of the metadata? (data entry error?)
```{r}
mysteries <- list(molec = molec, homog_vols = homog_vols, 
                  surface_area = surface_area, chl = chl, 
                  afdw = afdw, picurve = picurve, sym_counts = sym_counts, 
                  tac = tac, protein = protein) %>%
 map(~ .[!. %in% coral_metadata])

mysteries
```

## Which samples in metadata are missing from each dataset?
```{r}
completeness <- list(molec = molec, homog_vols = homog_vols, 
                     surface_area = surface_area, chl = chl, 
                     afdw = afdw, picurve = picurve, sym_counts = sym_counts, 
                     tac = tac, protein = protein) %>%
  map(~ coral_metadata %in% .) %>%
  as_tibble() %>%
  mutate(colony_id = coral_metadata) %>%
  select(colony_id, everything())

completeness %>%
  select(-1) %>%
  map(~ coral_metadata[. == FALSE])
```

# Full completeness table
```{r}
completeness %>% print(n = nrow(.))
write.table(completeness, file="output/3_completeness.csv", sep=",")
```


